name: fullstack-application-vue

dashboard:
  component: '@serverless/tencent-website'
  inputs:
    code:
      src: dist
      root: dashboard
      hook: npm run build
    env:
      apiUrl: ${api.url}
      # domain: www.serverlessmetrics.com # Insert your custom domain here

api:
  component: '@serverless/tencent-express'
  inputs:
    code: ./api
    functionName: fullstack-vue-api
    apigatewayConf:
      protocol: https
