name: fullstack-application-postgres

frontend:
  component: '@serverless/tencent-website'
  # more configuration for @serverless/tencent-website,
  # refer to: https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md
  inputs:
    region: ${env.REGION}
    protocol: https
    code:
      src: dist
      root: frontend
      hook: npm run build
      envPath: src
    env:
      # get api url after below api service deployed.
      apiUrl: ${api.url}

api:
  component: '@serverless/tencent-express'
  # more configuration for @serverless/tencent-website,
  # refer to: https://github.com/serverless-components/tencent-express/blob/master/docs/configure.md
  inputs:
    region: ${env.REGION}
    code: ./api
    functionName: fullstack-api-pg
    role: ServerlessRole
    functionConf:
      timeout: 30
      vpcConfig:
        vpcId: ${vpc.vpcId}
        subnetId: ${vpc.subnetId}
      environment:
        variables:
          PG_CONNECT_STRING: ${postgresql.connects.private}
    apigatewayConf:
      protocols:
        - http
        - https

postgresql:
  component: '@serverless/tencent-postgresql'
  inputs:
    region: ${env.REGION}
    zone: ${env.ZONE}
    dBInstanceName: serverless
    extranetAccess: false
    vpcConfig:
      vpcId: ${vpc.vpcId}
      subnetId: ${vpc.subnetId}

vpc:
  component: '@serverless/tencent-vpc'
  inputs:
    region: ${env.REGION}
    zone: ${env.ZONE}
    vpcName: serverlessVpc
    subnetName: serverlessSubnet
